default: true

# Multiple headings with the same content
MD024: false
MD046: false
line_length:
  line_length: 120
  tables: false
no-hard-tabs: false
whitespace: false
html: false
ul-indent:
  indent: 4
