name: conan-docker-tools-modern

x-common-args: &common-args
  DISTRO_VERSION: ${DISTRO_VERSION}
  NINJA_VERSION: ${NINJA_VERSION}
  CMAKE_VERSION: ${CMAKE_VERSION}
  GCC_VERSION: ${GCC_VERSION}
  CLANG_VERSION: ${CLANG_VERSION}
  USERNAME: ${USERNAME}
  USER_UID: ${USER_UID}
  USER_GID: ${USER_GID}
  MOLD_VERSION: ${MOLD_VERSION}

services:
  clang_gcc:
    platform: ${PLATFORM}
    build:
      context: clang_gcc
      dockerfile: Dockerfile
      args:
        <<: *common-args
    environment:
      IMAGE_NAME: ${IMAGE_NAME}
    image: ${IMAGE_NAME}
    container_name: clang_gcc
    tty: true
